env:
  global:
    - SHELLCHECK_OPTS="-e SC1090 -e SC1091"
matrix:
  include:
    - language: bash
      script:
        - shellcheck --version
        - bash -c 'shopt -s globstar nullglob; shellcheck --format=gcc ./scripts/**/*.{sh,ksh,bash}'
    - language: ruby
      install: true
      script: true
