env:
  global:
    - SHELLCHECK_OPTS="-e SC1090 -e SC1091"
matrix:
  include:
    - language: bash
      script:
        - shellcheck --version
        - for file in $(find ./scripts -type f); do shellcheck --format=gcc $file; done;
    - language: ruby
      install: true
      script: true
