matrix:
  include:
    - language: bash
      script:
        - for file in $(find ./scripts -type f); do shellcheck --format=gcc $file; done;
    - language: ruby
      install: true
      script: true
